CREATE TABLE users
(id SERIAL PRIMARY KEY,
 first_name VARCHAR(50),
 last_name VARCHAR(50),
 email VARCHAR(50) NULL,
 facebook_id VARCHAR(300) NULL,
 admin BOOLEAN DEFAULT false,
 last_login TIMESTAMP NOT NULL DEFAULT NOW(),
 created_at TIMESTAMP NOT NULL DEFAULT NOW());
